### ISSUE TITLE
"npm install gun-db" fails with incorrect SemVer# for gun dependency

### ISSUE THREAD

**Issue by Cyberider** [d3x0r/gun-db#3]
The latest version of gun is 0.9.96.

In the `package.json` file the gun version `^0.9.98` needs to be changed to `^0.9.96`

**Comment by d3x0r** [comment]
^0.9 ?

**Comment by d3x0r** [comment]
meh.. should have left it 0.96 and not just any 0.9 because that fails....
^0.9.96 it is (published and pushed)

**Comment by Cyberider** [comment]
Great that allowed npm to attempt to install your module but... it is failing on building your other package sack.vgs...

`../src/vfs_module.cc:955:37: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int num2 = (int)args[1]->ToNumber()->Value();
                                     ^
In file included from /home/default/.node-gyp/8.10.0/include/node/node.h:63:0,
                 from ../src/global.h:1,
                 from ../src/vfs_module.cc:2:
/home/default/.node-gyp/8.10.0/include/node/v8.h:9760:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^

At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning’
cc1plus: warning: unrecognized command line option ‘-Wno-misleading-indentation’
cc1plus: warning: unrecognized command line option ‘-Wno-implicit-fallthrough’
  CXX(target) Release/obj.target/sack_vfs/src/sack/sack.o
../src/sack/sack.cc:87286:27: fatal error: uuid/uuid.h: No such file or directory
compilation terminated.
sack_vfs.target.mk:179: recipe for target 'Release/obj.target/sack_vfs/src/sack/sack.o' failed
make: *** [Release/obj.target/sack_vfs/src/sack/sack.o] Error 1
make: Leaving directory '/home/default/MEGA/DEV/Dev/nodes/gunDB_testing2/node_modules/sack.vfs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/default/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/home/default/.nvm/versions/node/v8.10.0/bin/node" "/home/default/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/default/MEGA/DEV/Dev/nodes/gunDB_testing2/node_modules/sack.vfs
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN gundb_testing2@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sack.vfs@0.9.121 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sack.vfs@0.9.121 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/default/.npm/_logs/2018-03-11T04_27_29_068Z-debug.log
`

**Comment by d3x0r** [comment]
Ya that either needs uuid-dev ... (name varies depending on distro) it's really from ext2fs -util or something....

uuid/uuid.h

**Comment by Cyberider** [comment]
`../src/sack/sack.cc:87286:27: fatal error: uuid/uuid.h: No such file or directory`

When I look for "uuid/uuid.h" in sack.cc it is seems to be # prefixed out for documentation? Also there is no `../src/uuid/uuid.h` directory to be found. Am I confused?

```
DECLARATION_END
#endif
#  else
#    include <uuid/uuid.h>
#  endif
SQL_NAMESPACE
#  ifdef __INTERNAL_UUID__
CTEXTSTR GetGUID( void )

```


I'm trying to find clues. In your `sack.vfs/.travis.yml` file it shows a need for you project to include uuid-dev in its build:
```
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - uuid-dev
```
However a `npm search uuid-dev` finds no matches for it.

**Comment by d3x0r** [comment]
what is your system?
https://rpmfind.net/linux/rpm2html/search.php?query=uuid-devel
https://aur.archlinux.org/packages/uuid/

Yes, I don't by default include the local version, relying instead on the system version.

**Comment by Cyberider** [comment]
Ubuntu.
`> apt search uuid-dev` found a match. I installed it.
Now when I `> npm install gun-db` it works (but throws lots of deprecated warnings and other warnings).
Thanks

**Comment by d3x0r** [comment]
Just an FYI

https://github.com/d3x0r/sack (original sources library sources) sack.vfs is the Node/V8 C++ interface sources plus an amalgamation of source from sack.

https://github.com/d3x0r/SACK/tree/master/src/contrib/uuid-1.6.2
https://github.com/d3x0r/SACK/tree/master/src/contrib  Other sources from other sources which may be includes as snapshots of their various versions...

I *could* include UUID; (and had to for android amalgamation) but then it would end up compiling against that .... 

sack/makefiles/prog/ppc - this is a Pre-Processor for C; once upon a time compilers didn't implement __VA_ARGS__ for variadic macros; I realized to get a single output basically I could list all the C sources as input to the preprocessor, it would handle multiple-inclusions of the same header and only echo it once... then don't include any compiler or system headers so #include gets generated for things not found, and basically don't process #define substutions but leave those instead.  It does end up reformatting for indentation, and because of how comments are gathered they get pulled out of lines and gathered before the the line.
